version: '3.3'

networks:
  default_network:
    external: true

services:
  test_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - default_network

#  bot:
#    build:
#      context: .
#    command: python bot.py
#    env_file:
#      - .env
#    volumes:
#      - .:/app
#    expose:
#      - "8003"
#    ports:
#      - "8003:8003"
#    depends_on:
#      - web
#    networks:
#      - default_network

